### ISSUE TITLE
Document some guidelines for the asciidoc documentation

### ISSUE THREAD

**Issue by luminize** [machinekit/machinekit-docs#11]
It would be wise to have some preferred way of making headers so it's easy to have the second pair of C4 eyes looking at a PR like me merging #10 while @zultron had some remarks.

**Comment by zultron** [comment]
It's ok.  If it matters enough to me (it doesn't) or anyone else, a follow-up PR can be submitted.  That seems like enough process to cover this corner case.

**Comment by luminize** [comment]
ok, i'll close this then and anybody who does get bothered enough can re-open it.
