### ISSUE TITLE
New Docs site lacks mention on the Blog

### ISSUE THREAD

**Issue by cdsteinkuehler** [machinekit/machinekit-docs#140]
Someone should craft a glowing blog post about the new documentation changes.  I will do so if necessary, but I'd rather it come from one of the group who actually did a good chunk of the work.  I was barely able to keep up with the issue emails you were all working so fast!  :)

...and GREAT JOB EVERYONE!  It's super exciting to see all the changes!

**Comment by ArcEye** [comment]
I am using my new found blog credentials to pen something right now

**Comment by ArcEye** [comment]
Done

**Comment by cdsteinkuehler** [comment]
Looks great!  Thanks!
