### ISSUE TITLE
Website text boxes have poor contrast

### ISSUE THREAD

**Issue by cdsteinkuehler** [machinekit/machinekit-docs#144]
I am having problems reading the default textboxes rendered on the website.  The black on dark-gray and turquoise on dark gray have very little contrast.  Is this what it looks like for everyone else?

![textbox](https://cloud.githubusercontent.com/assets/1993109/15690811/e977ab26-274a-11e6-9e1e-0cde7fd6d19c.png)

**Comment by mhaberler** [comment]
same here

we need to reconsider site style, and that is just  one aspect

font - looks flashy, readabiliy: poor IMO
screen real estate efficiency - poor, narrow center column, lots of wasted space
shading, quoted text background color - not so great

**Comment by luminize** [comment]
@cdsteinkuehler @mhaberler Yes, I agree.

The green/yellow of the logo is not my personal taste, but I can live with that.
What is less attractive is the yellow background of code blocks. Plus literal `code` in the text is another shade of yellow. 

Like looking into a bowl of custard ;)

My take is "less is more" good reading is more important than rounded corners and colors.

We can search a bit on Jekyll templates and see what's out there to form an opinion.

**Comment by ArcEye** [comment]
PR #157 goes a long way to resolve

Highlights now custard-cream not custard-vomit
![selection_009](https://cloud.githubusercontent.com/assets/770392/15787128/707d58ea-29b8-11e6-9f4b-4ca635c1f347.png)

Tables now high contrast background
![selection_007](https://cloud.githubusercontent.com/assets/770392/15787144/824a8a20-29b8-11e6-8a06-2329e3d161c9.png)

[NOTE] a peaceful graduated blue
![selection_008](https://cloud.githubusercontent.com/assets/770392/15787155/962740ba-29b8-11e6-94de-dc115b0f4ced.png)

[WARNING] a bit more strident but not glaring
![selection_006](https://cloud.githubusercontent.com/assets/770392/15787180/aa3e2b36-29b8-11e6-97df-87024b9566d0.png)

**Comment by ArcEye** [comment]
Wrong button
