### ISSUE TITLE
Machine Kit Folder Structure Docs

### ISSUE THREAD

**Issue by DuNuNuBatman** [machinekit/machinekit-docs#153]
In the developer documentation, could you add a brief overview of the folders in the machinekit source? For example, I was looking at the source to find the code for the GCode interpreter as shown in the architecture overview diagram, but I'm not sure where to start. Or what is the purpose of the nc_files folder?

**Comment by ArcEye** [comment]
I don't think this will happen any time soon.  The source code is a bit outside the scope of the docs.

I would suggest you ask on the forum if you cannot find the answers yourself, but do try to find them first or you may get shot down if they are readily available.

This is a talk Michael gave which covers the area  of the interpreter
https://plus.google.com/events/c35prtt5ptrbmcc292bmhiketuc

The purpose of the nc_files folder?  To contain the numerical control example files.
Why it is not in /configs, the only place it is used, I don't know
