### ISSUE TITLE
There are still issues in github.machinekit.io

### ISSUE THREAD

**Issue by luminize** [machinekit/machinekit-docs#178]
Since all documentation, including the source for the site now reside in machinekit-docs, and machinekit.github.io is only used for displaying the site, should we move/close issues on machinekit.github.io to machinekit-docs, and disable the possibility of making issues on machinekit.github.io repo?

https://github.com/machinekit/machinekit.github.io/issues/60
https://github.com/machinekit/machinekit.github.io/issues/61

**Comment by mhaberler** [comment]
yes we should remove the tracker from this repo, and refer to mk/mk-docs

**Comment by luminize** [comment]
relevant issues have been brought into this repo. I have disables the possibility to file issues at machinekit/machinekit.github.io
