### ISSUE TITLE
wiki : no picture

### ISSUE THREAD

**Issue by LETARTARE** [machinekit/machinekit-docs#23]
Hello,
I have no picture on my browser  'Seamonkey 2.33.1' ?
Kind regards

**Comment by luminize** [comment]
@LETARTARE i fail to see what you mean with this issue.

**Comment by LETARTARE** [comment]
Oh, yes, here is a copy of the result:
![gaphical_user](https://cloud.githubusercontent.com/assets/5158475/8549041/def8d5ce-24c8-11e5-9d53-15eea71d0029.png)
Figure 2 does not appear !

**Comment by luminize** [comment]
ok, don't use the wiki.
you need to view the repo itself, like here:
https://github.com/machinekit/machinekit-docs/blob/master/src/common/user_intro.asciidoc

if this solves your issue, would you close it?
thanks

**Comment by LETARTARE** [comment]
Do I try to change the path of Wiki images ?

**Comment by zultron** [comment]
@luminize, did you just shut off the wiki?  I can't even bring up the OP's link.  Good!  (But I'm confused)

**Comment by luminize** [comment]
@zultron yes i did (disable wiki). Imo it has no use since the wiki is yet another repo. And contributions should be made in the repo itself and not the wiki.

**Comment by zultron** [comment]
Great!  I did this on other MK repos at one point, but maybe the MK-docs wiki was created later.  I'll make another check.  Thanks, Bas.

**Comment by luminize** [comment]
Hi John,
Yes it was. I transferred this repo from my account to the MK organization. I dabbled with the Wiki in the beginning when I got the docs out of the MK code base and I guess this was a leftover from that experiment.
One of the problems with the wiki was as the OP mentioned that the pictures couldn't be displayed.
Bas
