### ISSUE TITLE
Website source has 15k+ blank lines

### ISSUE THREAD

**Issue by darenschwenke** [machinekit/machinekit-docs#303]
View source: www.machinekit.io/docs/man/man9/kins/
It's nearly 30k lines long.  I didn't count, but I'm guessing at least 50% of that is whitespace/newlines.
I think perhaps consecutive blank lines need to be stripped on save if not inside a strict formatting section.

**Comment by ArcEye** [comment]
Afraid I really don't see the problem.
The spacing makes it clear and easy to read.

As for being 30,000 lines long :confused: 

kins.asciidoc is 113 lines long and only 3343 bytes.

**Comment by cdsteinkuehler** [comment]
On 2/23/2019 5:36 AM, ArcEye wrote:
> Afraid I really don't see the problem.
> The spacing makes it clear and easy to read.
> 
> As for being 30,000 lines long :confused: 
> 
> kins.asciidoc is 113 lines long and only 3343 bytes.

I see the problem.  The html rendered by the page is 29652 lines long,
most of which is a bunch of blank lines in the <ul> lists which make
up the menu on the right-hand side of the page.

The HTML for the kins itself looks sensible and is less than 200 lines.

...so the issue isn't really with kins, it's with the web navigation menu.

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by ArcEye** [comment]
OK, I see.

The html page is generated, sometimes several times a day, from the asciidoc and several css style sheets plus the added html content to create the overall page.

There is no human input outside of the asciidoc contents.
So long as the page looks how it should, the size of it is irrelevant to us and not something that can be edited.

**Comment by darenschwenke** [comment]
Ok.  Just made it _quite_ a bit harder when I went to go find HTML targets I could use for pointing people directly to a certain tagged section.  :) Thought you should know.
